// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tcEgressModeVal struct {
	Drop     uint8
	Proxy80  uint8
	Proxy443 uint8
	Pad      uint8
}

type tcLpm4Key struct {
	Prefixlen uint32
	Data      uint32
}

type tcPolicyKey struct {
	Src uint32
	Dst uint32
}

type tcPolicyPortKey struct {
	Src  uint32
	Dst  uint32
	Port uint16
	Dir  uint16
}

type tcPolicyVal struct {
	Generation uint64
	Flags      uint64
}

// loadTc returns the embedded CollectionSpec for tc.
func loadTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc: %w", err)
	}

	return spec, err
}

// loadTcObjects loads tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcObjects
//	*tcPrograms
//	*tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcSpecs struct {
	tcProgramSpecs
	tcMapSpecs
	tcVariableSpecs
}

// tcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcProgramSpecs struct {
	TcEgress  *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcMapSpecs struct {
	EgressAllow   *ebpf.MapSpec `ebpf:"egress_allow"`
	EgressDeny    *ebpf.MapSpec `ebpf:"egress_deny"`
	EgressMode    *ebpf.MapSpec `ebpf:"egress_mode"`
	EgressSlot    *ebpf.MapSpec `ebpf:"egress_slot"`
	FabricActive  *ebpf.MapSpec `ebpf:"fabric_active"`
	FlowEvents    *ebpf.MapSpec `ebpf:"flow_events"`
	FlowSample    *ebpf.MapSpec `ebpf:"flow_sample"`
	Host4         *ebpf.MapSpec `ebpf:"host4"`
	HostAddrs4    *ebpf.MapSpec `ebpf:"host_addrs4"`
	IpcacheV0     *ebpf.MapSpec `ebpf:"ipcache_v0"`
	IpcacheV1     *ebpf.MapSpec `ebpf:"ipcache_v1"`
	NodeUlaV0     *ebpf.MapSpec `ebpf:"node_ula_v0"`
	NodeUlaV1     *ebpf.MapSpec `ebpf:"node_ula_v1"`
	PolicyPortsV0 *ebpf.MapSpec `ebpf:"policy_ports_v0"`
	PolicyPortsV1 *ebpf.MapSpec `ebpf:"policy_ports_v1"`
	PolicyV0      *ebpf.MapSpec `ebpf:"policy_v0"`
	PolicyV1      *ebpf.MapSpec `ebpf:"policy_v1"`
	Private4      *ebpf.MapSpec `ebpf:"private4"`
	ProxyPorts    *ebpf.MapSpec `ebpf:"proxy_ports"`
	SlotUla       *ebpf.MapSpec `ebpf:"slot_ula"`
}

// tcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcVariableSpecs struct {
}

// tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcObjects struct {
	tcPrograms
	tcMaps
	tcVariables
}

func (o *tcObjects) Close() error {
	return _TcClose(
		&o.tcPrograms,
		&o.tcMaps,
	)
}

// tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcMaps struct {
	EgressAllow   *ebpf.Map `ebpf:"egress_allow"`
	EgressDeny    *ebpf.Map `ebpf:"egress_deny"`
	EgressMode    *ebpf.Map `ebpf:"egress_mode"`
	EgressSlot    *ebpf.Map `ebpf:"egress_slot"`
	FabricActive  *ebpf.Map `ebpf:"fabric_active"`
	FlowEvents    *ebpf.Map `ebpf:"flow_events"`
	FlowSample    *ebpf.Map `ebpf:"flow_sample"`
	Host4         *ebpf.Map `ebpf:"host4"`
	HostAddrs4    *ebpf.Map `ebpf:"host_addrs4"`
	IpcacheV0     *ebpf.Map `ebpf:"ipcache_v0"`
	IpcacheV1     *ebpf.Map `ebpf:"ipcache_v1"`
	NodeUlaV0     *ebpf.Map `ebpf:"node_ula_v0"`
	NodeUlaV1     *ebpf.Map `ebpf:"node_ula_v1"`
	PolicyPortsV0 *ebpf.Map `ebpf:"policy_ports_v0"`
	PolicyPortsV1 *ebpf.Map `ebpf:"policy_ports_v1"`
	PolicyV0      *ebpf.Map `ebpf:"policy_v0"`
	PolicyV1      *ebpf.Map `ebpf:"policy_v1"`
	Private4      *ebpf.Map `ebpf:"private4"`
	ProxyPorts    *ebpf.Map `ebpf:"proxy_ports"`
	SlotUla       *ebpf.Map `ebpf:"slot_ula"`
}

func (m *tcMaps) Close() error {
	return _TcClose(
		m.EgressAllow,
		m.EgressDeny,
		m.EgressMode,
		m.EgressSlot,
		m.FabricActive,
		m.FlowEvents,
		m.FlowSample,
		m.Host4,
		m.HostAddrs4,
		m.IpcacheV0,
		m.IpcacheV1,
		m.NodeUlaV0,
		m.NodeUlaV1,
		m.PolicyPortsV0,
		m.PolicyPortsV1,
		m.PolicyV0,
		m.PolicyV1,
		m.Private4,
		m.ProxyPorts,
		m.SlotUla,
	)
}

// tcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcVariables struct {
}

// tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcPrograms struct {
	TcEgress  *ebpf.Program `ebpf:"tc_egress"`
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *tcPrograms) Close() error {
	return _TcClose(
		p.TcEgress,
		p.TcIngress,
	)
}

func _TcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_x86_bpfel.o
var _TcBytes []byte
