// Package server 是 agent 的 gRPC 服务实现（M1.4）。
// 依赖方向：server -> machine / image / info / state，反向禁止。
package server

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/kernel/hypeman/lib/images"
	"github.com/zhu327/firepaas/internal/agent/info"
	"github.com/zhu327/firepaas/internal/agent/machine"
	"github.com/zhu327/firepaas/internal/agent/mutation"
	"github.com/zhu327/firepaas/internal/agent/state"
	contracts "github.com/zhu327/firepaas/internal/contracts/agentv1"
	pb "github.com/zhu327/firepaas/shared/gen/agent/v1"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Server 聚合 InfoService / MachineService / ImageService。
type Server struct {
	pb.UnimplementedInfoServiceServer
	pb.UnimplementedMachineServiceServer
	pb.UnimplementedImageServiceServer
	pb.UnimplementedSnapshotServiceServer
	pb.UnimplementedVolumeServiceServer

	machines  *machine.Adapter
	ledger    *state.Ledger
	fences    *state.Fences
	mutations *mutation.Protocol
	info      *info.Provider
	creds     *state.Creds // M4：proxy credential 验证材料（仅摘要，ADR-0006）

	// M4：强制要求 create 携带 proxy credential（兼容开关，默认 true）。
	requireCredential bool

	// diskWatermark（v1.1，ADR-0018）：PullImage（部署预取）的磁盘水位守护，
	// 已用比例 ≥ 该值时拒绝预取（0 = 不启用；create 路径不受影响）。
	diskWatermark float64

	// admissionDiskWatermark（v1.2-E，ADR-0035）：create 硬准入的磁盘水位
	//（默认 0.9）。与 diskWatermark 分开配置：预取是可让步的优化，create
	// 是业务请求但同样不能把 data 盘写爆。
	admissionDiskWatermark float64

	// P3-7：在途 create 的资源计数。admit 的快照（实例 Size 之和）只能
	// 看到已落地的 machine；并发 create 在“检查→落地”窗口内互相不可见，
	// 会同时通过准入（TOCTOU）。单写者串行派发下不可达，但硬准入是
	// “不越过资源硬上限”的最后防线，不能依赖上游行为。
	inflightVCPU atomic.Int64
	inflightMem  atomic.Int64
	inflightDisk atomic.Int64 // v1.2-E（ADR-0035）：在途 create 的磁盘承诺

	// R2-8：在途 volume 预算（MiB）。create volume / dataset import / overlay
	// 的节点级硬准入此前各自只看已落地 volume——「检查→落地」窗口内并发
	// 请求互相不可见会同时越过水位。与 create 的 inflight 计数同型
	//（先加后查），统一计入 admitVolume 的已承诺量。
	inflightVolumeDisk atomic.Int64

	// runtimeLimits/runtimeSem（v1.2-C，ADR-0025）：logs/exec/cp 会话限制。
	runtimeLimits runtimeLimits
	runtimeSem    sessionSem

	// inventoryEpoch is unique per agent process. Together with the monotonic
	// generation it lets the control plane reject delayed observations while
	// treating an agent restart as a new sequence.
	inventoryEpoch      string
	inventoryGeneration atomic.Uint64
}

// New 构造 Server。fences 提供 generation 高水位（P0-2）：
// 变更请求先查 ledger 幂等（重放返回原结果），再校验/推进 generation fence。
// New 构造 Server。fences 提供 generation 高水位（P0-2）；creds 为 M4 proxy
// credential 验证材料（可 nil = 不校验，仅测试用）。opts 可选扩展。
func New(
	machines *machine.Adapter,
	ledger *state.Ledger,
	fences *state.Fences,
	info *info.Provider,
	opts ...Option,
) *Server {
	s := &Server{
		machines: machines, ledger: ledger, fences: fences,
		mutations: mutation.New(ledger, fences), info: info,
		requireCredential: true, runtimeLimits: defaultRuntimeLimits(),
		inventoryEpoch: fmt.Sprintf("%d-%p", time.Now().UnixNano(), machines),
	}
	for _, o := range opts {
		o(s)
	}
	// 会话信号量在构造时创建（并发 handler 惰性初始化有数据竞争，且
	// 重写字段会让旧信号量上的 release 永久阻塞）。
	s.runtimeSem = make(sessionSem, s.runtimeLimits.maxSessions)
	return s
}

// Option 定制 Server（M4：向后兼容的可选参数）。
type Option func(*Server)

// WithCreds 注入验证材料存储（nil 之外）。同时关闭强制校验时用 WithCredentialRequired。
func WithCreds(c *state.Creds) Option { return func(s *Server) { s.creds = c } }

// WithCredentialRequired 控制 create 是否强制携带 proxy credential。
func WithCredentialRequired(v bool) Option { return func(s *Server) { s.requireCredential = v } }

// WithInventoryEpoch makes inventory ordering deterministic in tests. Production
// uses a process-unique value generated by New.
func WithInventoryEpoch(epoch string) Option {
	return func(s *Server) {
		if strings.TrimSpace(epoch) != "" {
			s.inventoryEpoch = epoch
		}
	}
}

// WithDiskWatermark 设置 PullImage（部署预取）的磁盘水位守护
// （已用比例 ≥ v 时拒绝预取；0 = 不启用）。
func WithDiskWatermark(v float64) Option { return func(s *Server) { s.diskWatermark = v } }

// WithAdmissionDiskWatermark（v1.2-E，ADR-0035）设置 create 硬准入的
// 磁盘水位（≤0 = 默认 0.9）。
func WithAdmissionDiskWatermark(v float64) Option {
	return func(s *Server) {
		if v <= 0 {
			v = 0.9
		}
		s.admissionDiskWatermark = v
	}
}

// ServiceInfo 实现 InfoService。
func (s *Server) ServiceInfo(context.Context, *emptypb.Empty) (*pb.ServiceInfoResponse, error) {
	return s.info.Response(), nil
}

// CreateMachine 实现带 fencing/幂等的创建。
func (s *Server) CreateMachine(ctx context.Context, req *pb.CreateMachineRequest) (*pb.CreateMachineResponse, error) {
	if err := contracts.ValidateCreateRequest(req); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	if s.creds != nil && s.requireCredential && req.GetProxyCredential() == "" {
		return nil, status.Error(
			codes.InvalidArgument,
			"missing proxy_credential (execution-bound traffic token required)",
		)
	}
	out, err := mutation.RunCreateMachine(s.mutations, mutation.CreateMachine[*pb.CreateMachineResponse]{
		Identity: mutation.Identity{
			OperationID: req.GetOperationId(),
			MachineID:   req.GetMachineId(),
			ExecutionID: req.GetSpec().GetExecutionId(),
			Generation:  req.GetGeneration(),
			RequestHash: hashRequest(req),
		},
		Prepare: func() (func(), error) {
			wantVCPU, wantMem, wantDisk := admitSize(req)
			s.inflightVCPU.Add(int64(wantVCPU))
			s.inflightMem.Add(int64(wantMem))
			s.inflightDisk.Add(int64(wantDisk))
			release := func() {
				s.inflightVCPU.Add(-int64(wantVCPU))
				s.inflightMem.Add(-int64(wantMem))
				s.inflightDisk.Add(-int64(wantDisk))
			}
			if err := s.admit(req); err != nil {
				release()
				return nil, err
			}
			return release, nil
		},
		Recover: func() (mutation.Recovery[*pb.CreateMachineResponse], error) {
			// 崩溃窗口恢复：按 hypeman inventory 查找本操作的产物（Name
			// == machine_id，且 execution/generation tags 匹配）。找到 = 认领
			// 上次已创建的实例；找不到 = 重跑 Effect（协议层保证不会二次撞名）。
			m, found, err := s.machines.RecoverMachine(
				ctx,
				req.GetMachineId(),
				req.GetSpec().GetExecutionId(),
				req.GetGeneration(),
			)
			return mutation.Recovery[*pb.CreateMachineResponse]{
				Value: &pb.CreateMachineResponse{Machine: m},
				Found: found,
			}, err
		},
		Effect: func() (*pb.CreateMachineResponse, error) {
			m, err := s.machines.Create(ctx, req)
			return &pb.CreateMachineResponse{Machine: m}, err
		},
		PersistCredential: func() error {
			if s.creds != nil && req.GetProxyCredential() != "" {
				// Ensure：首次落地与重放补写共用（已存同值摘要时不重写）。
				return s.creds.Ensure(
					req.GetMachineId(),
					req.GetSpec().GetExecutionId(),
					state.Digest(req.GetProxyCredential()),
				)
			}
			return nil
		},
		Codec: protoCodec(func() *pb.CreateMachineResponse { return &pb.CreateMachineResponse{} }),
	})
	if err != nil {
		if errors.Is(err, machine.ErrImageNotFound) || errors.Is(err, machine.ErrImageTooBig) ||
			errors.Is(err, machine.ErrSecretEnvInjectionUnsupported) ||
			errors.Is(err, machine.ErrSecretSnapshotForbidden) {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
		return nil, mutationError(err)
	}
	return out, nil
}

// dropCredential 撤销 machine 的 proxy 验证材料；落盘失败不再静默——残留
// 条目无功能危害（machine 已删，下次同 id create 会覆盖），但需可见。
func (s *Server) dropCredential(machineID string) {
	if s.creds == nil {
		return
	}
	if err := s.creds.Drop(machineID); err != nil {
		slog.Warn("credential drop failed; stale digest lingers until retention window",
			"machine_id", machineID, "error", err)
	}
}

// ListMachines 实现列表（M1 无分页）。
func (s *Server) ListMachines(ctx context.Context, req *pb.ListMachinesRequest) (*pb.ListMachinesResponse, error) {
	if req == nil {
		return nil, status.Error(codes.InvalidArgument, "request is required")
	}
	machines, err := s.machines.List(ctx, req.ProjectId)
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	return &pb.ListMachinesResponse{Machines: machines}, nil
}

// DeleteMachine 实现带 fencing/幂等的删除。adapter.Delete 已是分阶段可恢复
// 语义（R2）：VM 不存在只代表 runtime 阶段完成，其余阶段照常补做——因此
// agent 侧不再返回 NotFound，已完成的幂等收敛与 controller 的“NotFound 视作
// 删除成功”决策等价。阶段失败 warn-log（adapter 内）并聚合为 Internal
// （controller 决策表的非永久性错误 = 重试；重放的同 operation claim 重跑
// 剩余阶段）。
func (s *Server) DeleteMachine(ctx context.Context, req *pb.DeleteMachineRequest) (*emptypb.Empty, error) {
	if err := contracts.ValidateDeleteRequest(req); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	replayed, err := mutation.RunDeleteMachine(s.mutations, mutation.DeleteMachine{
		Identity: mutation.Identity{
			OperationID: req.GetOperationId(),
			MachineID:   req.GetMachineId(),
			ExecutionID: req.GetExecutionId(),
			Generation:  req.GetGeneration(),
			RequestHash: hashRequest(req),
		},
		Effect: func() error {
			if err := s.machines.Delete(ctx, req.GetMachineId(), req.GetExecutionId(), req.GetGeneration()); err != nil {
				if errors.Is(err, machine.ErrExecutionMismatch) {
					// 确定性门禁（instances tags 属于其他 execution）：重试
					// 永不收敛——映射 FailedPrecondition，让 controller 按
					// execution 已经换代/仍有效分流，而不是无限 requeue。
					return status.Errorf(codes.FailedPrecondition, "delete execution mismatch: %v", err)
				}
				// Internal 在 controller 决策表中是非永久性错误（重试）；
				// 同 operation 的重法会重跑剩余未完成的阶段。
				return status.Errorf(codes.Internal, "staged delete of %s incomplete (retry): %v",
					req.GetMachineId(), err)
			}
			return nil
		},
		DropCredential: func() { s.dropCredential(req.GetMachineId()) },
	})
	_ = replayed
	if err != nil {
		return nil, mutationError(err)
	}
	return &emptypb.Empty{}, nil
}

// admit 硬准入：allocated + inflight ≤ R·capacity（CPU R=4，内存/磁盘
// R=1.0，与 scheduler 同一语义；容量未知时拒绝，保守不破坏硬上限承诺）。
// inflight 含本请求（P3-7 先加后查）；memTotal 已含 host 保留扣减（P3-8）。
// v1.2-E（ADR-0035）：磁盘双层检查——requested 承诺不超盘容量（不超售）
// + 真实水位（disk_used/data_total ≥ admission 磨盘水位）拦截，控制面
// 投影滞后/泄漏时这里是最终防线。
func (s *Server) admit(req *pb.CreateMachineRequest) error {
	if req.GetSpec() == nil {
		return status.Error(codes.InvalidArgument, "spec is required")
	}
	vcpuTotal, memTotal, vcpuAllocated, memAllocated, resourcesValid := s.info.AdmissionSnapshot()
	// R2（契约 D-1）：资源采集无效 = 没有 live 样本也没有 ≤60s 的
	// last-known-good。此时把“采集失败”当 0 占用会在硬准入里放行 ghost
	// 超售——fail closed；非 create RPC（List/生命周期等）不经过本检查。
	if !resourcesValid {
		return status.Error(codes.Unavailable,
			"resource inventory unavailable (no fresh last-known-good); admission fail-closed")
	}
	if vcpuTotal == 0 || memTotal == 0 {
		return status.Error(codes.ResourceExhausted, "node capacity unknown, admission denied")
	}
	inflVCPU := uint64(s.inflightVCPU.Load())
	inflMem := uint64(s.inflightMem.Load())
	if float64(vcpuAllocated+inflVCPU) > float64(vcpuTotal)*4 {
		return status.Errorf(codes.ResourceExhausted,
			"cpu admission: allocated %d + inflight %d exceeds 4x%d", vcpuAllocated, inflVCPU, vcpuTotal)
	}
	if memAllocated+inflMem > memTotal {
		return status.Errorf(codes.ResourceExhausted,
			"mem admission: allocated %dMiB + inflight %dMiB exceeds %dMiB", memAllocated, inflMem, memTotal)
	}
	// 磁盘：requested 承诺（有效值与调度/预约同源，contracts.DefaultDiskMib）。
	diskTotal, diskAllocated := s.info.DiskAdmissionSnapshot()
	inflDisk := uint64(s.inflightDisk.Load())
	// inflDisk 已包含当前请求（CreateMachine 在调用 admit 前登记），不得再加
	// diskMib；否则每个 create 的磁盘请求都会被双算。
	if diskTotal > 0 && diskAllocated+inflDisk > diskTotal {
		return status.Errorf(codes.ResourceExhausted,
			"disk admission: allocated %dMiB + inflight %dMiB exceeds %dMiB",
			diskAllocated, inflDisk, diskTotal)
	}
	// 磁盘：真实水位（最终防线；data 盘不可 statfs 时跳过）。
	if diskTotal > 0 && s.admissionDiskWatermark > 0 {
		if frac := diskStatsFraction(s.info.DataDir()); frac >= s.admissionDiskWatermark {
			return status.Errorf(codes.ResourceExhausted,
				"disk admission: watermark %.2f reached (%.2f)", s.admissionDiskWatermark, frac)
		}
	}
	return nil
}

// admitSize 返回请求的归一化资源需求（与 controller 默认值一致）。
// v1.2-E：磁盘 0 → contracts.DefaultDiskMib（与调度/预约同源）。
func admitSize(req *pb.CreateMachineRequest) (vcpu, memMib, diskMib uint64) {
	vcpu = req.GetSpec().GetVcpu()
	memMib = req.GetSpec().GetMemMib()
	if vcpu == 0 {
		vcpu = 1
	}
	if memMib == 0 {
		memMib = 512
	}
	diskMib = contracts.EffectiveDiskMib(req.GetSpec().GetDiskMib())
	return vcpu, memMib, diskMib
}

// hashRequest 生成 request hash。只用于幂等比较，不持久化敏感字段。
// CreateMachineRequest 的 secret_env / proxy_credential 是单向下发的一次性
// 字段（ADR-0006/0010）：重派时控制面会重新解析引用值、凭证按需现算，
// 二者不参与幂等比较——首次执行的成功结果仍按 ledger 原样重放。
func hashRequest(msg proto.Message) string {
	switch req := msg.(type) {
	case *pb.CreateMachineRequest:
		cp := proto.Clone(req).(*pb.CreateMachineRequest)
		cp.SecretEnv = nil
		cp.ProxyCredential = ""
		msg = cp
	case *pb.ForkSnapshotRequest:
		cp := proto.Clone(req).(*pb.ForkSnapshotRequest)
		cp.ProxyCredential = ""
		msg = cp
	case *pb.RestoreSnapshotRequest:
		cp := proto.Clone(req).(*pb.RestoreSnapshotRequest)
		cp.ProxyCredential = ""
		msg = cp
	}
	raw, err := protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}.Marshal(msg)
	if err != nil {
		return fmt.Sprintf("hash-error-%v", err)
	}
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])
}

// PauseMachine / ResumeMachine（M4.5 scale-to-zero，mvp-plan §8.4）：
// R2 起走 claimed mutation（与 create/delete 共享 LockMachine 串行化）：
// durable claim → 未完成 claim 的重试经 ConvergePause/ConvergeResume 从实例
// 实际状态恢复收敛 → 幂等 Effect → fence Advance → durable Complete。
// suspend 期间 observed PAUSED 不摘路由？——由 controller 决策：proxy 端首个
// 请求触发同步 restore（autoresume），路由保留但请求有唤醒延迟。
func (s *Server) PauseMachine(ctx context.Context, req *pb.PauseMachineRequest) (*pb.Machine, error) {
	op := req.GetOperation()
	if op == nil || op.MachineId == "" || op.ExecutionId == "" || op.OperationId == "" {
		return nil, status.Error(
			codes.InvalidArgument,
			"operation with machine_id/execution_id/operation_id is required",
		)
	}
	out, err := mutation.RunLifecycle(s.mutations, s.machineLifecycle(op, hashRequest(req),
		func() (*pb.Machine, error) { return s.machines.Pause(ctx, op.MachineId, op.ExecutionId) },
		func() (mutation.Recovery[*pb.Machine], error) {
			m, found, err := s.machines.ConvergePause(ctx, op.MachineId, op.ExecutionId)
			return mutation.Recovery[*pb.Machine]{Value: m, Found: found}, err
		}))
	if err != nil {
		if errors.Is(err, machine.ErrSecretSnapshotForbidden) {
			return nil, status.Error(codes.FailedPrecondition, err.Error())
		}
		return nil, mutationError(err)
	}
	return out, nil
}

func (s *Server) ResumeMachine(ctx context.Context, req *pb.ResumeMachineRequest) (*pb.Machine, error) {
	op := req.GetOperation()
	if op == nil || op.MachineId == "" || op.ExecutionId == "" || op.OperationId == "" {
		return nil, status.Error(
			codes.InvalidArgument,
			"operation with machine_id/execution_id/operation_id is required",
		)
	}
	out, err := mutation.RunLifecycle(s.mutations, s.machineLifecycle(op, hashRequest(req),
		func() (*pb.Machine, error) { return s.machines.Resume(ctx, op.MachineId, op.ExecutionId) },
		func() (mutation.Recovery[*pb.Machine], error) {
			m, found, err := s.machines.ConvergeResume(ctx, op.MachineId, op.ExecutionId)
			return mutation.Recovery[*pb.Machine]{Value: m, Found: found}, err
		}))
	if err != nil {
		if errors.Is(err, mutation.ErrConflict) {
			return nil, mutationError(err)
		}
		return nil, status.Error(codes.FailedPrecondition, err.Error())
	}
	return out, nil
}

// machineLifecycle 构造 pause/resume 的 claimed mutation 参数（identity + 效果
// + 崩溃窗口恢复收敛由调用方给出）。
func (s *Server) machineLifecycle(
	op *pb.MachineOperationRequest,
	requestHash string,
	effect func() (*pb.Machine, error),
	recover func() (mutation.Recovery[*pb.Machine], error),
) mutation.Lifecycle[*pb.Machine] {
	return mutation.Lifecycle[*pb.Machine]{
		Identity: mutation.Identity{
			OperationID: op.OperationId,
			MachineID:   op.MachineId,
			ExecutionID: op.ExecutionId,
			Generation:  op.Generation,
			Kind:        "machine.lifecycle",
			RequestHash: requestHash,
		},
		Recover: recover,
		Effect:  effect,
		Codec:   protoCodec(func() *pb.Machine { return &pb.Machine{} }),
	}
}

// ---------------------------------------------------------------------------
// ImageService（v1.1，ADR-0018 部署预取）
// ---------------------------------------------------------------------------

// diskStatsFraction 返回 dataDir 所在文件系统已用比例（0-1）；不可用时返回 0。
func diskStatsFraction(dataDir string) float64 {
	total, used := diskStats(dataDir)
	if total == 0 {
		return 0
	}
	return float64(used) / float64(total)
}

// diskStats 复用 info 包的 statfs 逻辑（避免重复实现）。
func diskStats(dataDir string) (totalMib, usedMib uint64) {
	if dataDir == "" {
		dataDir = "/"
	}
	var stat syscall.Statfs_t
	if err := syscall.Statfs(dataDir, &stat); err != nil {
		return 0, 0
	}
	bsize := uint64(stat.Bsize)
	total := stat.Blocks * bsize
	free := stat.Bfree * bsize
	return total / mib, (total - free) / mib
}

const mib = 1024 * 1024

// PullImage 确保镜像就绪（幂等）。v1.1 部署预取的 agent 侧入口：
// 控制面在 rollout PREPARING 前向 top-K 候选节点异步下发，失败/超时不
// 阻塞 rollout（尽力而为）。磁盘水位守护：已用比例 ≥ watermark 时拒绝
// （capacity-model 既有约束；imageretention GC 为兜底）。
func (s *Server) PullImage(ctx context.Context, req *pb.PullImageRequest) (*pb.PullImageResponse, error) {
	if req.GetImageRef() == "" {
		return nil, status.Error(codes.InvalidArgument, "image_ref is required")
	}
	if s.diskWatermark > 0 && s.info != nil {
		if frac := diskStatsFraction(s.info.DataDir()); frac >= s.diskWatermark {
			return nil, status.Errorf(codes.ResourceExhausted,
				"prefetch rejected: disk usage %.1f%% >= watermark %.1f%%", frac*100, s.diskWatermark*100)
		}
	}
	if err := s.machines.EnsureImage(ctx, req.GetImageRef()); err != nil {
		if errors.Is(err, machine.ErrImageNotFound) {
			return nil, status.Error(codes.NotFound, err.Error())
		}
		if errors.Is(err, machine.ErrImageTooBig) {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
		return nil, status.Error(codes.Internal, err.Error())
	}
	digest, sizeMib := s.machines.ImageInfo(ctx, req.GetImageRef())
	return &pb.PullImageResponse{ImageRef: req.GetImageRef(), Digest: digest, SizeMib: sizeMib}, nil
}

// ListImages returns ready local image entries with a deletable full reference.
func (s *Server) ListImages(ctx context.Context, _ *pb.ListImagesRequest) (*pb.ListImagesResponse, error) {
	cached, err := s.machines.CachedImages(ctx)
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	out := make([]*pb.PullImageResponse, 0, len(cached))
	for _, img := range cached {
		sizeMib := uint64(0)
		if img.SizeBytes != nil && *img.SizeBytes > 0 {
			sizeMib = uint64(*img.SizeBytes) / mib
		}
		out = append(out, &pb.PullImageResponse{ImageRef: img.Name, Digest: img.Digest, SizeMib: sizeMib})
	}
	return &pb.ListImagesResponse{Images: out}, nil
}

// DeleteImage removes an unused local cache entry. Not-found is idempotent;
// references from any local instance are rejected by the adapter.
func (s *Server) DeleteImage(ctx context.Context, req *pb.DeleteImageRequest) (*emptypb.Empty, error) {
	if strings.TrimSpace(req.GetImageRef()) == "" {
		return nil, status.Error(codes.InvalidArgument, "image_ref is required")
	}
	if err := s.machines.DeleteImage(ctx, req.GetImageRef()); err != nil {
		if errors.Is(err, images.ErrNotFound) {
			return &emptypb.Empty{}, nil
		}
		return nil, status.Error(codes.FailedPrecondition, err.Error())
	}
	return &emptypb.Empty{}, nil
}
